apps/adopcion/urls.py
from django.urls import path
from apps.adopcion.views import solicitud_list, index_adopcion, SolicitudList, SolicitudCreate, SolicitudUpdate, SolicitudDelete
urlpatterns = [
    path('index', index_adopcion),
    path('solicitud/listar', solicitud_list, name='solicitud_listar'),
    path('solicitud/nueva', SolicitudCreate.as_view(), name='solicitud_crear'),
    path('solicitud/editar/<pk>', SolicitudUpdate.as_view(), name='solicitud_editar'),
    path('solicitud/eliminar/<pk>', SolicitudDelete.as_view(), name='solicitud_eliminar'),

]

refugio/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.adopcion.views import prueba
from django.contrib.auth.views import logout_then_login, LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('mascota/', include(('apps.mascota.urls',"mascota"), namespace="mascota")),
    path('adopcion/', include(('apps.adopcion.urls',"adopcion"), namespace="adopcion")),
    path('usuario/', include(('apps.usuario.urls',"usuario"), namespace="usuario")),
    path('accounts/login/', LoginView.as_view(template_name='index.html'), name= 'login'),
    path('logout/', logout_then_login, name= 'logout'),
    path('reset/password_reset/',
         PasswordResetView.as_view(
             template_name='resgistration/password_reset_form.html', 
             email_template_name='resgistration/password_reset_email.html',
         ),
         name='password_reset'),
    path('reset/password_reset_done',
         PasswordResetDoneView.as_view(
             template_name='resgistration/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('reset/password_reset_confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='resgistration/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('reset/password_reset_complete',
         PasswordResetCompleteView.as_view(
             template_name='resgistration/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('prueba', prueba, name='prueba'),
]

apps/adopcion/models.py
from django.db import models
from django.utils.translation import ugettext as _
# Create your models here.
class Persona(models.Model):
     
     nombre = models.CharField(max_length=50)
     apellidos = models.CharField(max_length=70)
     edad = models.IntegerField()
     telefono = models.CharField(max_length=12)
     email = models.EmailField()
     domicilio = models.TextField()
     def __str__(self):
        return '{} {}'.format(self.nombre, self.apellidos) 

class Solicitud(models.Model):
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    numero_mascotas = models.IntegerField()
    razones = models.TextField()
    
    class Meta():
        permissions ={
            ('is_admin', _('is admin')),
            ('is_empleado', _('is empleado')),



        }

apps/adopcion/forms.py
from django import forms
from apps.adopcion.models import Persona, Solicitud

class PersonaForm(forms.ModelForm):
    class Meta:
        model = Persona
        
        fields = [
            'nombre',
            'apellidos',
            'edad',
            'telefono',
            'email',
            'domicilio',

        ]
        labels = {
            'nombre': 'Nombre',
            'apellidos': 'Apellidos',
            'edad': 'Edad',
            'telefono': 'Telefono',
            'email': 'Email',
            'domicilio': 'Domicilio',

        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'apellidos': forms.TextInput(attrs={'class':'form-control'}),
            'edad': forms.TextInput(attrs={'class':'form-control'}),
            'telefono': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.TextInput(attrs={'class':'form-control'}),
            'domicilio': forms.Textarea(attrs={'class':'form-control'}),

        }
class SolicitudForm(forms.ModelForm):
    class Meta:
        model = Solicitud
        
        fields = [
            'numero_mascotas',
            'razones',

        ]
        labels = {
            'numero_mascotas': 'Numero de mascotas',
            'razones': 'Razones',

        }
        widgets = {
            'numero_mascotas': forms.TextInput(attrs={'class':'form-control'}),
            'razones': forms.Textarea(attrs={'class':'form-control'}),
            

        }

apps/adopcion/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from apps.adopcion.models import Persona, Solicitud
from apps.adopcion.forms import PersonaForm, SolicitudForm
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Q
from django.db.models import Count
# Create your views here.
def index_adopcion(request):
    return HttpResponse("Soy la pagina principal de la app adopcion")
@login_required
def prueba(request):
     user=request.user
     if user.has_perm('adopcion.is_empleado'):
         return HttpResponseRedirect(reverse_lazy('mascota:mascota_list'))
     elif user.has_perm('adopcion.is_admin'):
         return HttpResponseRedirect(reverse_lazy('adopcion:solicitud_listar'))
     else:
         return HttpResponse("No tienes permisos")
         
@permission_required('adopcion.is_admin')
def solicitud_list(request):
    queryset = request.GET.get('buscar')
    solicitud = Solicitud.objects.all().annotate(num_personas=Count('persona')).order_by('id')
    contexto = {'solicitudes':solicitud}
    if queryset:
        solicitud = Solicitud.objects.filter(
              Q(persona__nombre__icontains = queryset) |
              Q(razones__icontains = queryset)
        ).distinct().annotate(num_personas=Count('persona'))
        contexto = {'solicitudes':solicitud}
    return render(request, 'adopcion/solicitud_list.html', contexto)

class SolicitudList(ListView):
    model = Solicitud
    template_name = 'adopcion/solicitud_list.html'
 
class SolicitudCreate(CreateView):
    model = Solicitud
    template_name = 'adopcion/solicitud_form.html'
    form_class = SolicitudForm
    second_form_class = PersonaForm
    success_url = reverse_lazy('adopcion:solicitud_listar')
    def get_context_data(self, **kwargs):
        context = super(SolicitudCreate, self).get_context_data(**kwargs)
        if 'form' not in context:
           context['form'] = self.form_class(self.request.GET)
        if 'form2' not in context:
           context['form2'] = self.second_form_class(self.request.GET)
        return context
    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        form2 = self.second_form_class(request.POST)
        if form.is_valid() and form2.is_valid():
            solicitud = form.save(commit = False)
            solicitud.persona = form2.save()
            solicitud.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form, form2=form2))

class SolicitudUpdate(UpdateView):
    model =Solicitud
    second_model = Persona
    template_name = 'adopcion/solicitud_form.html'
    form_class = SolicitudForm
    second_form_class = PersonaForm
    success_url = reverse_lazy('adopcion:solicitud_listar')


    def get_context_data(self, **kwargs):
        context = super(SolicitudUpdate, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk', 0)
        solicitud = self.model.objects.get(id=pk)
        persona = self.second_model.objects.get(id=solicitud.persona_id)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class(instance=persona)
        context['id'] = pk
        return context
    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        id_solicitud = kwargs['pk']
        solicitud = self.model.objects.get(id=id_solicitud)
        persona = self.second_model.objects.get(id=solicitud.persona_id)
        form = self.form_class(request.POST, instance = solicitud)
        form2 = self.second_form_class(request.POST, instance=persona)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save() 
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(self.get_success_url())

class SolicitudDelete(DeleteView):
    model = Solicitud
    template_name = 'adopcion/solicitud_delete.html'
    success_url = reverse_lazy('adopcion:solicitud_listar')

templates/adopcion/index.html
{% extends 'base/base.html' %}
{% block title %}
App mascota
{% endblock %}

{% block content %}
<h5>Este es el contenido de mascota</h5>
{% endblock %}
{% block footer %}
<h5>Este es el footer de mascota</h5>
{% endblock %}

templates/adopcion/solicitud_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form  method="post">
{% csrf_token %}
<h3>Desea eliminar el solicitud de {{object.persona.nombre}} {{object.persona.apellidos}}</h3>
<button class="btn btn-danger" type="submit">Si, eliminar</button>
<a class="btn btn-default"href="{% url 'adopcion:solicitud_listar' %}">Cancelar</a>
</form>
{% endblock %}

templates/adopcion/solicitud_form.html
{% extends 'base/base.html' %}

{% block content %}
<form  method="post">
{% csrf_token %}
<div class="row">

<div class="col-md-8 col-md-offset-2">
<div class="form-group">
<label for="{{form2.nombre.name}}">{{form2.nombre.label}}</label>
{{form2.nombre}}
</div>
</div>
<div class="col-md-8 col-md-offset-2">
<div class="form-group">
<label for="{{form2.apellidos.name}}">{{form2.apellidos.label}}</label>
{{form2.apellidos}}
</div>
</div>
<div class="col-md-8 col-md-offset-2">
<div class="form-group">
<label for="{{form2.edad.name}}">{{form2.edad.label}}</label>
{{form2.edad}}
</div>
</div>
<div class="col-md-8 col-md-offset-2">
<div class="form-group">
<label for="{{form2.email.name}}">{{form2.email.label}}</label>
{{form2.email}}
</div>
</div>

<div class="col-md-8 col-md-offset-2">
<div class="form-group">
<label for="{{form2.telefono.name}}">{{form2.telefono.label}}</label>
{{form2.telefono}}
</div>
</div>

<div class="col-md-8 col-md-offset-2">
<div class="form-group">
<label for="{{form2.domicilio.name}}">{{form2.domicilio.label}}</label>
{{form2.domicilio}}
</div>
</div>

<div class="col-md-8 col-md-offset-2">
<div class="form-group">
<label for="{{form.numero_mascotas.name}}">{{form.numero_mascotas.label}}</label>
{{form.numero_mascotas}}
</div>
</div>

<div class="col-md-8 col-md-offset-2">
<div class="form-group">
<label for="{{form.razones.name}}">{{form.razones.label}}</label>
{{form.razones}}
</div>
</div>

</div>
<button type="submit">Guardar</button>
</form>
{% endblock %}

templates/adopcion/solicitud_list.html
{% extends 'base/base.html'%}

{% block content %}

<table class="table table-bordered">

  <thead>
<tr>
   

    <td>No. solicitud</td>

    <td>Adoptante</td>
  <td>No. mascota</td>

    <td>Razones</td>
<td>No Solicitantes</td>

   
<td>acciones</td>
  </tr>
  </thead>

  <tbody>
{% if solicitudes %}
{% for solicitud in solicitudes %}
<tr>

    <td>{{solicitud.id}}</td>

    <td>{{solicitud.persona.nombre}} {{solicitud.persona.apellidos}}</td>

 <td>{{solicitud.numero_mascotas}}</td>

    <td>{{solicitud.razones}}</td>
<td>{{solicitud.num_personas}}</td>

<td><a class="btn btn-primary"href="{% url 'adopcion:solicitud_editar' solicitud.id %}">Editar</a></td>
<td><a class="btn btn-danger"href="{% url 'adopcion:solicitud_eliminar' solicitud.id %}">Eliminar</a></td>

</tr>
{% endfor %}
{% else %}
<h1>No hay registros de mascotas</h1>
{% endif %}
  </tbody>

</table>

{% endblock %}