apps/adopcion/urls.py
from django.urls import path
from apps.adopcion.views import solicitud_list, index_adopcion, SolicitudList, SolicitudCreate, SolicitudUpdate, SolicitudDelete
urlpatterns = [
    path('index', index_adopcion),
    path('solicitud/listar', solicitud_list, name='solicitud_listar'),
    path('solicitud/nueva', SolicitudCreate.as_view(), name='solicitud_crear'),
    path('solicitud/editar/<pk>', SolicitudUpdate.as_view(), name='solicitud_editar'),
    path('solicitud/eliminar/<pk>', SolicitudDelete.as_view(), name='solicitud_eliminar'),

]

apps/mascota/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from apps.mascota.views import importar, listado, index, mascota_view, mascota_list, mascota_edit, mascota_delete, \
 MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete
urlpatterns = [
    path('', index, name='index'),
    path('nuevo', login_required(MascotaCreate.as_view()), name='mascota_crear'),
    path('listar', login_required(mascota_list), name='mascota_list'),
    path('editar/<pk>', login_required(MascotaUpdate.as_view()), name='mascota_edit'),
    path('eliminar/<pk>', login_required(MascotaDelete.as_view()), name='mascota_eliminar'),
    path('listado', listado, name='listado'),
    path('import', importar , name='import'),
]

refugio/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.adopcion.views import prueba
from django.contrib.auth.views import logout_then_login, LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('mascota/', include(('apps.mascota.urls',"mascota"), namespace="mascota")),
    path('adopcion/', include(('apps.adopcion.urls',"adopcion"), namespace="adopcion")),
    path('usuario/', include(('apps.usuario.urls',"usuario"), namespace="usuario")),
    path('accounts/login/', LoginView.as_view(template_name='index.html'), name= 'login'),
    path('logout/', logout_then_login, name= 'logout'),
    path('reset/password_reset/',
         PasswordResetView.as_view(
             template_name='resgistration/password_reset_form.html', 
             email_template_name='resgistration/password_reset_email.html',
         ),
         name='password_reset'),
    path('reset/password_reset_done',
         PasswordResetDoneView.as_view(
             template_name='resgistration/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('reset/password_reset_confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='resgistration/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('reset/password_reset_complete',
         PasswordResetCompleteView.as_view(
             template_name='resgistration/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('prueba', prueba, name='prueba'),
]

templates/base/base.html
<!DOCTYPE html>
<html>
<head>
{% block extrastatic %}
{% endblock %}
{% load static %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<title>{% block title %}Page Title {% endblock %}</title>
</head>
<body>
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
     
 <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Mascota
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'mascota:mascota_crear'%}">Registrar</a>
          <a class="dropdown-item" href="{% url 'mascota:mascota_list'%}">Listar</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Adopcion
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'adopcion:solicitud_crear'%}">solicitar</a>
          <a class="dropdown-item" href="{% url 'adopcion:solicitud_listar'%}">Listar</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'logout'%}">logout</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" name= "buscar" value="{{request.GET.buscar}}" placeholder="Buscar" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{% endblock %}
{% block header %}
{% include 'base/header.html' %}
{% endblock %}
{% block content %}
<p>My first paragraph.</p>
{% endblock %}
{% block footer %}
<h5>Footer</h5>
{% endblock %}
<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
{% block extrajs %}
{% endblock %}
</body>
</html>

templates/base/header.html
<header>
hola
</header>