apps/mascota/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from apps.mascota.views import importar, listado, index, mascota_view, mascota_list, mascota_edit, mascota_delete, \
 MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete
urlpatterns = [
    path('', index, name='index'),
    path('nuevo', login_required(MascotaCreate.as_view()), name='mascota_crear'),
    path('listar', login_required(mascota_list), name='mascota_list'),
    path('editar/<pk>', login_required(MascotaUpdate.as_view()), name='mascota_edit'),
    path('eliminar/<pk>', login_required(MascotaDelete.as_view()), name='mascota_eliminar'),
    path('listado', listado, name='listado'),
    path('import', importar , name='import'),
]

refugio/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.adopcion.views import prueba
from django.contrib.auth.views import logout_then_login, LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('mascota/', include(('apps.mascota.urls',"mascota"), namespace="mascota")),
    path('adopcion/', include(('apps.adopcion.urls',"adopcion"), namespace="adopcion")),
    path('usuario/', include(('apps.usuario.urls',"usuario"), namespace="usuario")),
    path('accounts/login/', LoginView.as_view(template_name='index.html'), name= 'login'),
    path('logout/', logout_then_login, name= 'logout'),
    path('reset/password_reset/',
         PasswordResetView.as_view(
             template_name='resgistration/password_reset_form.html', 
             email_template_name='resgistration/password_reset_email.html',
         ),
         name='password_reset'),
    path('reset/password_reset_done',
         PasswordResetDoneView.as_view(
             template_name='resgistration/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('reset/password_reset_confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='resgistration/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('reset/password_reset_complete',
         PasswordResetCompleteView.as_view(
             template_name='resgistration/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('prueba', prueba, name='prueba'),
]

apps/mascota/models.py
from django.db import models
from apps.adopcion.models import Persona

# Create your models here.
class Vacuna(models.Model):
    nombre = models.CharField(max_length=50)
    def __str__(self):
        return '{}'.format(self.nombre) 
class Mascota(models.Model):
    nombre = models.CharField(max_length=50)
    sexo = models.CharField(max_length=50)
    edad_aproximada = models.IntegerField()
    fecha_rescate = models.DateField()
    persona = models.ForeignKey(Persona, null = True, blank = True, on_delete= models.CASCADE)
    vacuna = models.ManyToManyField(Vacuna, blank = True)

apps/mascota/forms.py
from django import forms
from apps.mascota.models import Mascota

class MascotaForm(forms.ModelForm):
    class Meta:
        model = Mascota
        
        fields = [
            'nombre',
            'sexo',
            'edad_aproximada',
            'fecha_rescate',
            'persona',
            'vacuna',

        ]
        labels = {
            'nombre': 'Nombre',
            'sexo': 'Sexo',
            'edad_aproximada': 'Edad aproximada',
            'fecha_rescate': 'Fecha rescate',
            'persona': 'Adoptante',
            'vacuna': 'Vacuna',

        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'sexo': forms.TextInput(attrs={'class':'form-control'}),
            'edad_aproximada': forms.TextInput(attrs={'class':'form-control'}),
            'fecha_rescate': forms.TextInput(attrs={'class':'form-control'}),
            'persona': forms.Select(attrs={'class':'form-control'}),
            'vacuna': forms.CheckboxSelectMultiple(),

        }

apps/mascota/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota
from django.urls import reverse_lazy
from django.core import serializers
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.db.models import Q
from django.contrib.auth.decorators import login_required, permission_required
from django.core.paginator import Paginator
from django.db.models import Count
from tablib import Dataset 
from apps.mascota.resources import MascotaResource
# Create your views here.
def listado(request):
    lista = serializers.serialize('json', Mascota.objects.all(), fields=['nombre', 'sexo'])
    return HttpResponse(lista, content_type= 'application/json')
def index(request):
    return render(request, "mascota/index.html")

def mascota_view(request):
    if request.method == 'POST':
        form = MascotaForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('mascota:index')

    else:
        form = MascotaForm()
    return render(request, 'mascota/mascota_form.html',{'form':form})
@permission_required('adopcion.is_empleado')
def mascota_list(request):
    queryset = request.GET.get('buscar')
    mascota = Mascota.objects.all().annotate(num_vacunas=Count('vacuna')).order_by('id')
   
    if queryset:
        mascota = Mascota.objects.filter(
              Q(nombre__icontains = queryset) |
              Q(sexo__icontains = queryset)
        ).distinct().annotate(num_vacunas=Count('vacuna')).order_by('id')
    paginator = Paginator(mascota, 2)
    page = request.GET.get('page')
    mascota = paginator.get_page(page)
    contexto = {'mascotas':mascota}

    return render(request, 'mascota/mascota_list.html', contexto)

def mascota_edit(request, id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == 'GET':
         form = MascotaForm(instance=mascota)
    else: 
        form = MascotaForm(request.POST, instance=mascota)
        if form.is_valid():
            form.save()
        return redirect('mascota:mascota_list')
    return render(request, 'mascota/mascota_form.html', {'form':form})
def mascota_delete(request, id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == 'POST':
        mascota.delete()
        return redirect('mascota:mascota_list')
    return render(request, 'mascota/mascota_delete.html', {'mascota':mascota})

class MascotaList(ListView):
    model = Mascota
    template_name = 'mascota/mascota_list.html'
    paginate_by = 2
    def get_queryset(self, **kwargs):
      queryset = self.request.GET.get('buscar')
      mascota = Mascota.objects.all().order_by('id')
    
      if queryset:
          mascota = Mascota.objects.filter(
              Q(nombre__icontains = queryset) |
              Q(sexo__icontains = queryset)
          ).distinct()
      return mascota
        
    
       
class MascotaCreate(CreateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_list')
class MascotaUpdate(UpdateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'mascota/mascota_form.html'
    success_url = reverse_lazy('mascota:mascota_list')

class MascotaDelete(DeleteView):
    model = Mascota
    template_name = 'mascota/mascota_delete.html'
    success_url = reverse_lazy('mascota:mascota_list')
def importar(request):  
   #template = loader.get_template('export/importar.html')  
   if request.method == 'POST':  
     mascota_resource = MascotaResource()  
     dataset = Dataset()  
     #print(dataset) 
     nuevas_mascotas = request.FILES['xlsfile'] 
     #print(nuevas_mascotas)
     imported_data = dataset.load(nuevas_mascotas.read())  
     print(imported_data['nombre'])  
     print(mascota_resource) 
     result = mascota_resource.import_data(dataset, dry_run=True) # Test the data import  
     print(result.has_errors())  
     if not result.has_errors():  
       mascota_resource.import_data(dataset, dry_run=False) # Actually import now  
   return render(request, 'export/importar.html')

templates/mascota/index.html
{% extends 'base/base.html' %}
{% block title %}
App mascota
{% endblock %}

{% block content %}
<h5>Este es el contenido de mascota</h5>
{% endblock %}
{% block footer %}
<h5>Este es el footer de mascota</h5>
{% endblock %}

templates/mascota/mascota_delete.html
{% extends 'base/base.html' %}

{% block content %}
<form  method="post">
{% csrf_token %}
<h3>Desea eliminar el registro de {{object.nombre}}</h3>
<button class="btn btn-danger" type="submit">Si, eliminar</button>
<a class="btn btn-default"href="{% url 'mascota:mascota_list' %}">Cancelar</a>
</form>
{% endblock %}

templates/mascota/mascota_form.html
{% extends 'base/base.html' %}

{% block content %}
<form  method="post">
{% csrf_token %}
{{form.as_p}}
<button type="submit">Guardar</button>
</form>
{% endblock %}

templates/mascota/mascota_list.html
{% extends 'base/base.html'%}

{% block content %}

<table class="table table-bordered">

  <thead>
<tr>
    <td>#</td>

    <td>Nombre</td>

    <td>Sexo</td>
  <td>Edad</td>

    <td>Fecha de rescate</td>

    <td>Adoptante</td>
 <td>Numero de vacunas</td>
<td>acciones</td>
  </tr>
  </thead>

  <tbody>
{% if mascotas %}
{% for mascota in mascotas %}
<tr>

    <td>{{mascota.id}}</td>

    <td>{{mascota.nombre}}</td>

    <td>{{mascota.sexo}}</td>
 <td>{{mascota.edad_aproximada}}</td>

    <td>{{mascota.fecha_rescate}}</td>


    <td>{{mascota.persona.nombre}}{{mascota.persona.apellidos}}</td>
<td>{{mascota.num_vacunas}}</td>
<td>
{% for vacuna in mascota.vacuna.all %}
{{vacuna.nombre}}
{% endfor %}</td>
<td><a class="btn btn-primary"href="{% url 'mascota:mascota_edit' mascota.id %}">Editar</a></td>
<td><a class="btn btn-danger"href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a></td>

</tr>
{% endfor %}
{% else %}
<h1>No hay registros de mascotas</h1>
{% endif %}
  </tbody>

</table>
<ul class="list-group">
<li >
{% if mascotas.has_previous %}
<a href="?page={{mascotas.previous_page_number}}">Previous</a>
{% endif %}
</li>

<li >
{% if mascotas.has_next %}
<a href="?page={{mascotas.next_page_number}}">Next</a>
{% endif %}
</li>
</ul>

{% endblock %}